improve kubeconfig management

diff --git a/configs/sh_profile_custom b/configs/sh_profile_custom
--- a/configs/sh_profile_custom
+++ b/configs/sh_profile_custom
@@ -337,15 +337,38 @@ test -e "${HOME}/.iterm2_shell_integration.bash" && { source "${HOME}/.iterm2_sh
 
 # ADDS CUSTOM KUBECONFIG FILES TO CONTEXT
 # TO SWITCH CONTEXTS AND NAMESPACES USE https://github.com/ahmetb/kubectx
-if test -d ~/.kube; then
-	export KUBECONFIG=~/.kube/config
-	touch "$KUBECONFIG"
-	mkdir -p ~/.kube/custom-contexts
-	for file in $(find ~/.kube/custom-contexts/ -name '*.config' \( -type f -o -type l \)); do
-		file="$(echo "${file}" | sed "s/\/\//\//")" # replace double slashes to single
-		export KUBECONFIG="$KUBECONFIG:${file}"
+kube_reload() {
+	trap 'trap - ERR; return' ERR
+	silent="false"
+	while [ $# -gt 0 ]; do
+		case "$1" in
+			-s|--silent) silent="true" ;;
+			-h|--help) echo "Usage: kube-reload [-s|--silent]"; return 0 ;;
+			*) echo "Invalid option: $1"; echo "Usage: kube-reload [-s|--silent]"; return 1 ;;
+		esac
+		shift
 	done
-fi
+	[ "${silent}" = "false" ] && { echo "Reloading kubeconfigs . . ."; }
+	if test -d ~/.kube; then
+		export KUBECONFIG=~/.kube/config
+		touch "$KUBECONFIG"
+		custom_contexts_dir=~/.kube/custom-contexts
+		mkdir -p ~/.kube/custom-contexts
+		custom_contexts_dir="$(cd "${custom_contexts_dir}" && pwd)"
+		[ "${silent}" = "false" ] && { echo "Custom Contexts Directory: '${custom_contexts_dir}'"; }
+		for file in $(find ~/.kube/custom-contexts/ -name '*.config' \( -type f -o -type l \)); do
+			[ "${silent}" = "false" ] && { printf "\t${file}\n" | sed -E "s|${custom_contexts_dir}|\.|"; }
+			file="$(echo "${file}" | sed "s/\/\//\//")" # replace double slashes to single
+			export KUBECONFIG="$KUBECONFIG:${file}"
+		done
+		kubectl config view --raw >~/.kube/config
+		export KUBECONFIG=~/.kube/config
+		[ "${silent}" = "false" ] && { echo "All contexts successfully joined into '${KUBECONFIG}'"; }
+	fi
+	return 0
+}
+alias kube-reload="kube_reload"
+kube-reload -s
 
 # macOS HOMEBREW
 if type brew >/dev/null 2>&1; then
